### ISSUE TITLE
how to fetch public board pins to display on a user's website, in browser?

### ISSUE THREAD

**Issue by timjobdea** [pinterest/pinterest-api-demo#13]
hey pinterest api developers, 

so, I'd like to display public pins on a user's own website from her public pinterest board to anyone who visits her website, without any backend/oauth (these are public pins aren't they?). I have no idea about all the api magic I have to do - to get your /boards/denisetaranov/picturebook-inspiration/pins/ end point return anything other than cryptic error messages - in response to below:

```
<script>
  window.pAsyncInit = function() {
    PDK.init({
      appId: "4990673532588422306",
      cookie: true
    });

    var pins = [];
    PDK.request('/boards/denisetaranov/picturebook-inspiration/pins/', function (response) {
      if (!response || response.error) {
        console.log('Error occurred', response);
      } else {
        pins = pins.concat(response.data);
        console.log('pins',pins)
        if (response.hasNext) {
          response.next();
        }
      }
    });
  };

  (function(d, s, id){
    var js, pjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) {return;}
    js = d.createElement(s); js.id = id;
    js.src = "//assets.pinterest.com/sdk/sdk.js";
    pjs.parentNode.insertBefore(js, pjs);
  }(document, 'script', 'pinterest-jssdk'));
</script>
```

do you have a demo of this?

**Comment by timtaranov** [comment]
looks like I found pinterest board widget builder that seems like is what I need... and oauth authenticator that can get me the token to access api. closing this. thanks!
