### ISSUE TITLE
Users followers

### ISSUE THREAD

**Issue by wbashir** [pinterest/pinterest-api-demo#6]
How do you get the users followers from the current version of the API. Is this endpoint available?

**Comment by zackargyle** [comment]
Hey Warsame!

There is a `/v1/me/followers/` endpoint you can use. You will want to make sure you request the `read_relationships` permission when using oauth to get the token. You can try it on the [API Explorer](https://developers.pinterest.com/tools/api-explorer/) under the `Me` tab.

**Comment by wbashir** [comment]
@zackargyle 

Thanks for following up on this. I was actually looking for other users followers and not necessarily `me`. Is there a `/v1/users/someusers/followers/` ?
