### ISSUE TITLE
Pinning/Sharing Videos

### ISSUE THREAD

**Issue by ris0** [pinterest/pinterest-api-demo#8]
Hello,

Could you please tell me if it is possible for users to share/pin videos? More importantly, would the shared video become embedded inside the Pinterest board? For example, if the user 'pins' a video they found on my website, will they see a cover image with a link that redirects to my website or will they see an embedded video play that is streaming my content?

-Rich

**Comment by ris0** [comment]
As of right now, the pinterest button that I have built is simply returning an encoded URI that redirects to Pinterest.

`export function pinterestShare(content) {`
  `var result = "https://pinterest.com/pin/create/bookmarklet/?url="`
   `+ encodeURIComponent(content.url) + "&media="`
 `+ encodeURIComponent(content.media) + "&description="`
 `+ encodeURIComponent(content.message)`
 `window.open(result)`
`}`

**Comment by zackargyle** [comment]
Currently there is no support for saving video to Pinterest with the API. That is something we are actively discussing because we know it is becoming more and more important. But for now, the answer is no. Sorry, Rich!

**Comment by ris0** [comment]
Thank you for the prompt response Zack!

It’s great to hear that you’re actively discussing this! I’m looking forward to integrating this feature when it is ready!

Thanks again,
Rich
